{{get_doctype()}}<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"/><?php if(strpos($_SERVER['HTTP_USER_AGENT'],"MSIE")===FALSE){echo('<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">');}else{echo('<meta name="viewport" content="width=device-width"/>');}?><meta property="og:title" content="Generator sales &amp; service provider in Bangladesh"><meta property="og:type" content="article"><meta property="og:url" content="http://www.anikamachinery.com/products/index"><meta property="og:image" content="http://www.anikamachinery.com/img/logo.png"><link rel=”publisher” href="https://plus.google.com/111000198987546116078"><meta name="google-site-verification" content="1J38C-FkK8EgHlPLTtX2-IanS-8MyvXosIag0WA9kRM"/><meta name="description" content="{{dynadesc}}"/><meta name="keywords" content="{{dynakey}}"/><meta name="robots" content="{{dynarobot}}"/><meta name="googlebot" content="{{dynagooglebot}}"/><meta name="rating" content="general"/><meta name="author" content="/\/\unaz:+8801615577997,+8801915577997"/><title>{{get_title("")}}</title>{{ stylesheet_link('css/style.css') }}
<link rel="icon" type="image/x-icon" href="img/favicon.png"/><link rel="shortcut icon" href="img/favicon.png" type="image/x-icon"/><link rel='canonical' href='http://www.anikamachinery.com' /><link rel='shortlink' href='http://www.anikamachinery.com'/><base href="{{url.getBaseUri("")}}"/></head><body><main class="pr main"><section class="row"><article class="rc6"><div class="tal logos"><a href="http://www.anikamachinery.com"><img class="img" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="img/011.jpg" alt="anika machinery logo" title="Go to Anika Machinery Home"/></a></div></article><article class="rc6"><nav id="nav"><ul class="topnav" id="myTopnav"><li><a class="{% if router.getControllerName()=="" or router.getControllerName()~router.getActionName()=="index" %}{{"active"}}{% else %}{{""}}{% endif %}" href="index">Anika</a></li><li><a class="{% if router.getControllerName()=="products" %}{{"active"}}{% else %}{{""}}{% endif %}" href="products/index">Products</a></li><li><a class="{% if router.getActionName()=="services" %}{{"active"}}{% else %}{{""}}{% endif %}" href="index/services">Services</a></li><li><a class="{% if router.getActionName()=="aboutus" %}{{"active"}}{% else %}{{""}}{% endif %}" href="index/aboutus">Aboutus</a></li><li><a class="{% if router.getActionName()=="contact" %}{{"active"}}{% else %}{{""}}{% endif %}" href="index/contact">Contact</a></li><li class="icon"><a href="javascript:void(0);" class="fs" onclick="myFunction()">&#9776;</a></li></ul></nav>{#{elements.getMenu()}#}</article></section>{% block content %}{# Contents Page load Here #}{% endblock %}<section class="row mb0 bg6"><article class="rc12 bgf"><div class="rc3">&nbsp;</div><div class="rc6 tac"><h1 class="tac title">OUR BEST CLIENTS</h1><img class="img" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="img/customers2.png" alt="Customers"/></div><div class="rc3">&nbsp;</div></article><article class="rc6">

<footer class="row footer fxsmall marginB0">
<article class="rc3"><div class="txt_center">&nbsp;</div></article>
<article class="rc6 txt_center bold">
<br/><a href="javascript:void(0);">Aboutus</a> &vert; <a class="feedbacks" href="javascript:void(0);">Feedback</a> &vert; <a href="javascript:void(0);">Legal</a> &vert; <a class="contacts" href="mailto:webmaster.thundervoice@gmail.com">Contact</a><br/>this site based on peoples republic of bangladesh.<br/>
<?php $executionTime = round(microtime(true) - $_SERVER["REQUEST_TIME_FLOAT"],3);echo('page rendered in :'.$executionTime.' seconds'); ?> &vert; memory used <?php echo(round(memory_get_usage()/1048576,2).' MB'); ?>
</article>  
<article class="rc3">
    <ul class="copyright">      
            <li><img alt="Developer Logo" title="Developed by: Firefly&reg;" class="firefly" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo('data:image/png;base64,'.base64_encode(file_get_contents('img/bee.png'))); ?>" /><span class="dotfly"></span></li>
            <li><p class="vbar"></p></li>
            <li>
<a href="https://www.facebook.com/anikamachinery"><span class="ico-fb"></span></a> <a href="https://plus.google.com/111000198987546116078"><span class="ico-gplus"></span></a> <a href="https://www.linkedin.com/in/anikaMachinery"><span class="ico-linkedin"></span></a> <a href="sitemap"><span class="ico-sitemap"></span></a>
                <div class="bold"><?php function copyright($year = null){$cYear = (int) date('Y');if($year === null || $year >= $cYear){$result = $cYear;}else{$result = $year.' - '.$cYear;}echo('Anikamachinery<br>Copyright &copy; '.$result.'.<br/>All Rights Reserved.<br>Developed By: <a href="mailto:abc@gmail.com">FireFly</a>&reg;<br>Phalcon '.Phalcon\Version::get());}copyright('2016');?></div>
            </li>
        </ul>
</article>	
</footer>
	</article></section></main>{% if router.getActionName()=='contact' %}{{javascript_include("http://maps.google.com/maps/api/js?key=AIzaSyDWTQpi0GTmb6hoIjbBlcGYfZLAkaDmqLI&v=3")}}<noscript>Javascript may Disabled!</noscript>{{javascript_include("js/gmaps.js")}}<noscript>Javascript may Disabled!</noscript><script>map=new GMaps({div: '#map',lat: 23.718998,lng: 90.411881,zoom: 14});map.addMarker({lat: 23.718998,lng: 90.411881,zoom: 14,title: 'Anika Machinery',infoWindow:{content: '<p>Anika Machinery, 83, Sajeda Ali Plaza, Nawabpur, Dhaka.</p>'}});</script>{% endif %}{{ javascript_include("js/jquery-3.3.1.min.js") }}<noscript>Javascript may Disabled!</noscript>{{ javascript_include("js/jquery.js") }}<noscript>Javascript may Disabled!</noscript></body></html>